In [2]:
import numpy as np
print(np.__version__)


2.5.2


In [3]:
a=np.array([[1,2],[3,4]])
a.ndim



2

In [4]:
a.itemsize

8

In [5]:
a.dtype


dtype('int64')

In [6]:
a.size

4

In [7]:
np.ones((2,3,3,3))


array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [8]:
np.full((2,2),99,dtype='int32')

array([[99, 99],
       [99, 99]], dtype=int32)

In [9]:
np.random.rand(4,2)


array([[0.53581895, 0.32557311],
       [0.07749359, 0.199564  ],
       [0.89857594, 0.14246971],
       [0.4565876 , 0.95299987]])

In [10]:
np.random.rand(4,2)


array([[0.56062737, 0.47092387],
       [0.09116596, 0.30130684],
       [0.08213486, 0.33308055],
       [0.81952404, 0.94945494]])

In [11]:
np.random.randint(-8,7,size=(3,3))

array([[-7, -5,  1],
       [ 3, -1,  0],
       [ 1,  2,  0]])

In [12]:
np.identity(4)



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
a=np.array([[1,2,3]])
r=np.repeat(a,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [14]:
a=np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
z=np.zeros((3,3))
z[1,1]=9
a[1:-1,1:-1]=z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
a[2,2]=9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
for i in range(1,4):
 for j in range(1,4):
    a[i,j]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
a[[0,1,2,3],[1,2,3,4]]

array([1., 0., 0., 1.])

In [19]:
b=np.ones((6,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
b[[0,4,5],3:]=4
print(b)

[[1. 1. 1. 4. 4.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 4. 4.]
 [1. 1. 1. 4. 4.]]


In [21]:
newcol=np.array([9,9,9,9,9])
a=np.column_stack((a,newcol))
print(a)

[[1. 1. 1. 1. 1. 9.]
 [1. 0. 0. 0. 1. 9.]
 [1. 0. 0. 0. 1. 9.]
 [1. 0. 0. 0. 1. 9.]
 [1. 1. 1. 1. 1. 9.]]


In [22]:
ab=np.matmul(a,b)
print(ab)


[[14. 14. 14. 47. 47.]
 [11. 11. 11. 44. 44.]
 [11. 11. 11. 44. 44.]
 [11. 11. 11. 44. 44.]
 [14. 14. 14. 47. 47.]]


In [23]:
np.min(a)

np.float64(0.0)

In [24]:
np.max(a,axis=1)

array([9., 9., 9., 9., 9.])

In [25]:
a.reshape(3,10)

array([[1., 1., 1., 1., 1., 9., 1., 0., 0., 0.],
       [1., 9., 1., 0., 0., 0., 1., 9., 1., 0.],
       [0., 0., 1., 9., 1., 1., 1., 1., 1., 9.]])

In [26]:
np.linalg.det(ab)

np.float64(0.0)